name: Waka Readme

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: 4samsamAC/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BAR_STYLE: "svg"
          BAR_COLOR: "#a78bfa"
          BAR_TRACK_COLOR: "#a29bfe"
          BAR_RADIUS: "4"
          SHOW_LINES_OF_CODE: true
